In [ ]:
import numpy as np

# Basics

In [9]:
a = np.array([1,2,3],dtype = 'int16')
print(a)
b = np.array([[1,2,3],[4,5,6]])
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [10]:
# Get Shape
b.shape

(2, 3)

In [ ]:
# Data type
a.dtype

dtype('int16')

In [13]:
# Total size
a.nbytes

6

# Accessing and Changing specific elements, rows, columns

In [34]:
a = np.array([[1,2,3,4,5,6,7],[5,6,7,8,9,10,11]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 5  6  7  8  9 10 11]]


In [22]:
# Accessing 9 [r,c]
print(a[1,4])
print(a[-1,-3])

9
9


In [23]:
# Get a specific Row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
# Specific Column
a[:,3]

array([4, 8])

In [29]:
# Getting a sequence of data 
a[:,0:7:2]

array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11]])

In [36]:
a[1,4] = 40
print(a)

a[:,4] = 70
print(a)

a[:,4] = [10,20]
print(a)

[[ 1  2  3  4 70  6  7]
 [ 5  6  7  8 40 10 11]]
[[ 1  2  3  4 70  6  7]
 [ 5  6  7  8 70 10 11]]
[[ 1  2  3  4 10  6  7]
 [ 5  6  7  8 20 10 11]]


In [39]:
b = np.array([[[1,2],[2,9]],[[3,4],[4,5]]])
print(b)

[[[1 2]
  [2 9]]

 [[3 4]
  [4 5]]]


In [ ]:
# Getting some specific element
b[0,1,1]

np.int64(9)

# Different Types of Arrays

In [ ]:
# All zeros matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
a = np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
# All 1's matrix
np.ones((2,3),dtype = 'int16')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [ ]:
np.full((2,2),100)

array([[100, 100],
       [100, 100]], dtype=int16)

In [49]:
np.full(a.shape,100)

array([[100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100]])

In [51]:
# Random Decimal Numbers
np.random.random_sample(a.shape)


array([[0.07307829, 0.23672257, 0.1393496 , 0.06387125, 0.61523742,
        0.679455  , 0.61758426],
       [0.71225764, 0.95523878, 0.25629106, 0.02113876, 0.05363577,
        0.06256336, 0.22734556]])

In [65]:
# Random Integer Numbers
np.random.randint(4,7,size = (3,3))

array([[4, 4, 4],
       [4, 4, 4],
       [4, 6, 4]])

In [67]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr = np.copy(a)
print(arr)
arr_3 = np.repeat(a, 3, axis=0)
print(arr_3)

[[ 1  2  3  4 10  6  7]
 [ 5  6  7  8 20 10 11]]
[[ 1  2  3  4 10  6  7]
 [ 1  2  3  4 10  6  7]
 [ 1  2  3  4 10  6  7]
 [ 5  6  7  8 20 10 11]
 [ 5  6  7  8 20 10 11]
 [ 5  6  7  8 20 10 11]]


In [78]:
a = np.ones((5,5))
b = np.zeros((3,3))
b[1,1] = 9
print(b.shape)
a[1:4,1:4] = b
print(b)
print(a)

(3, 3)
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [79]:
a = np.array([1,2,3])
b = a 
print(b)
b[0] = 12
print(a)
print(b)

[1 2 3]
[12  2  3]
[12  2  3]


In [80]:
b = np.copy(a)
b[0] = 50
print(a)
print(b)

[12  2  3]
[50  2  3]


# Mathematics

In [82]:
a = np.array([1,2,3])

In [83]:
a + 2

array([3, 4, 5])

In [84]:
a/2

array([0.5, 1. , 1.5])

In [85]:
b = np.array([1,1,1])
a*2 + b

array([3, 5, 7])

In [86]:
print((a*2+b)**2)

[ 9 25 49]


In [89]:
np.sin(np.pi*(a*2+b))

array([3.67394040e-16, 6.12323400e-16, 8.57252759e-16])

In [88]:
np.cos(np.pi*(a*2+b))

array([-1., -1., -1.])

# Linear Algebra

In [93]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

print(a @ b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [94]:
c = 2 * np.identity(3)
np.linalg.det(c)

np.float64(7.999999999999998)